variables:
    DOCKER_TLS_CERTDIR: "/certs"
    IMAGE_TAG: shopware/development

stages:
    - analyze
    - unit
    - build

cache:
    key: "Eternal static key"
    paths:
        - .composer
        - .npm

default:
    image: composer:1.10
    before_script:
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-scripts --no-progress
        - composer install --ignore-platform-reqs --no-interaction --optimize-autoloader --no-suggest --no-progress --working-dir=dev-ops/analyze

Static Analysis:
    stage: analyze
    only:
        refs:
            - merge_requests
            - master
    script:
        - dev-ops/analyze/vendor/bin/ecs check src --config easy-coding-standard.php
        - dev-ops/analyze/vendor/bin/phpstan analyze --level 8 src
        - dev-ops/analyze/vendor/bin/psalm --diff --show-info=false

Unit:
    image: composer:1.10
    stage: unit
    only:
        refs:
            - merge_requests
            - master
    script:
        - vendor/bin/phpunit
            --configuration dev-ops/analyze
            --log-junit build/artifacts/phpunit.junit.xml
            --colors=never

    artifacts:
        reports:
            junit: build/artifacts/phpunit.junit.xml

.base:
    image: docker:18.09.7
    stage: build
    only:
        refs:
            - master
        changes:
            - dev-ops/docker/containers/**/*
    services:
        - name: docker:18.09.7-dind
          alias: docker
    dependencies:
        - Unit
    before_script:
        - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"
    script:
        - sed -ri -e "s!php-apache:7.2!php-apache:$PHP_VERSION!g" dev-ops/docker/containers/app/Dockerfile
        - docker build -t $IMAGE_TAG:$PHP_VERSION dev-ops/docker/containers/app
        - docker push $IMAGE_TAG:$PHP_VERSION

build:7.2:
    extends: .base
    variables:
        PHP_VERSION: "7.2"
    after_script:
        - docker tag $IMAGE_TAG:$PHP_VERSION $IMAGE_TAG:latest
        - docker push $IMAGE_TAG:latest

build:7.3:
    extends: .base
    variables:
        PHP_VERSION: "7.3"

build:7.4:
    extends: .base
    variables:
        PHP_VERSION: "7.4"

build:8.0:
    extends: .base
    variables:
        PHP_VERSION: "8.0"
